from collections import OrderedDict
from urllib.parse import urlparse


# Findings that are meaningful per endpoint/parameter.
ENDPOINT_SPECIFIC_TYPES = {
    "SQL Injection",
    "Reflected XSS",
    "Stored XSS",
    "DOM XSS",
    "SSRF",
    "Open Redirect",
    "XXE",
    "CSRF Protection",
}


def _normalize(value):
    if value is None:
        return None
    return str(value).strip().lower()


def _is_endpoint_specific(finding):
    return finding.get("type") in ENDPOINT_SPECIFIC_TYPES


def _get_endpoint(finding):
    return finding.get("url") or finding.get("endpoint")


def _get_endpoint_path(url):
    if not url:
        return None
    try:
        return urlparse(url).path or "/"
    except Exception:
        return None


def _finding_key(finding):
    finding_type = _normalize(finding.get("type"))
    name = _normalize(finding.get("name"))
    category = _normalize(finding.get("category"))
    parameter = _normalize(finding.get("parameter"))

    if _is_endpoint_specific(finding):
        endpoint = _normalize(_get_endpoint(finding))
        return (
            "endpoint-specific",
            finding_type,
            category,
            name,
            parameter,
            endpoint,
        )

    # Global/passive findings are grouped so the same control issue is not
    # repeated for every crawled endpoint.
    return (
        "global",
        finding_type,
        category,
        name,
        parameter,
    )


def _merge_finding(existing, finding):
    """Keep the strongest finding while filling missing intelligence fields."""
    confidence_order = {"low": 1, "medium": 2, "high": 3}

    existing_confidence = _normalize(existing.get("confidence"))
    new_confidence = _normalize(finding.get("confidence"))

    if confidence_order.get(new_confidence, 0) > confidence_order.get(
        existing_confidence, 0
    ):
        existing["confidence"] = finding.get("confidence")

    # Prefer reproduced/verified evidence over a plain observation.
    if finding.get("verification") == "reproduced":
        existing["verification"] = "reproduced"
        existing["verification_status"] = finding.get(
            "verification_status", "Reproduced"
        )

    # Preserve all finding-intelligence fields generated by scanner.py.
    for field in (
        "description",
        "recommendation",
        "detection",
        "evidence",
        "method",
        "test_mode",
        "cwe",
        "owasp",
        "impact",
        "verification_status",
    ):
        if not existing.get(field) and finding.get(field):
            existing[field] = finding.get(field)

    # Preserve useful active-verification metadata when present.
    for field in ("active_probe_count", "differential_change"):
        if finding.get(field) is not None and existing.get(field) is None:
            existing[field] = finding.get(field)

    return existing


def deduplicate_findings(findings):
    """
    Deduplicate findings without dropping scanner intelligence metadata.

    Important:
    scanner.py now adds CWE, OWASP, impact, confidence and verification
    information during normalization. This function must retain those fields
    because app.py performs a second deduplication before save_scan().
    """
    unique = OrderedDict()

    for finding in findings or []:
        if not isinstance(finding, dict):
            continue

        key = _finding_key(finding)
        endpoint_url = _get_endpoint(finding)
        endpoint_path = finding.get("endpoint") or _get_endpoint_path(endpoint_url)

        if key not in unique:
            item = dict(finding)

            # Normalize endpoint fields consistently for the UI/database.
            item["url"] = endpoint_url
            item["endpoint"] = endpoint_path

            # Ensure this is always available for passive/global findings too.
            item.setdefault("affected_endpoints", [])

            if endpoint_url and endpoint_url not in item["affected_endpoints"]:
                item["affected_endpoints"].append(endpoint_url)

            unique[key] = item
            continue

        item = _merge_finding(unique[key], finding)

        if endpoint_url:
            affected = item.setdefault("affected_endpoints", [])
            if endpoint_url not in affected:
                affected.append(endpoint_url)

        unique[key] = item

    return list(unique.values())
